version: '3.5'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: 'php:8.3-fpm'
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www/
        ports:
            - '9000:9000'
    nginx:
        image: 'nginx:alpine'
        ports:
            - '80:80'
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    postgres:
        image: 'postgres:alpine'
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=blog
        ports:
            - '5432:5432'
    redis:
        image: 'redis:latest'
        ports:
            - '6379:6379'
