name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: docker-compose up --build -d && docker compose exec app composer install && docker compose exec app php artisan migrate && docker compose exec app php artisan optimize:clear && docker compose exec app npm run build
